# Generated by Django 5.2.8 on 2025-12-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_album_genre_alter_albumreview_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='made_todays_album',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
