# Generated by Django 5.2.8 on 2025-12-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_album_cover_art_alter_album_made_todays_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='made_todays_album',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
