# Generated by Django 5.2.8 on 2026-01-06 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.constants import NAME_TO_EMAIL_LOOKUP


def forwards_func(apps, schema_editor):
    User = apps.get_model('common', 'User')
    Album = apps.get_model('common', 'Album')
    albums_to_update = []
    for album in Album.objects.all():
        user = User.objects.filter(email=NAME_TO_EMAIL_LOOKUP[album.submitted_by_deprecated]).first()
        if user:
            album.submitted_by_new = user
            albums_to_update.append(album)
    Album.objects.bulk_update(albums_to_update, ['submitted_by_new'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_album_made_todays_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='submitted_by',
            new_name='submitted_by_deprecated',
        ),
        migrations.AddField(
            model_name='album',
            name='submitted_by_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
