# Generated by Django 5.2.8 on 2026-01-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_submitted_by_album_submitted_by_deprecated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='submitted_by_new',
            new_name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='album',
            name='submitted_by_deprecated',
        ),
    ]
