# Generated by Django 5.2.8 on 2026-01-06 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_rename_submitted_by_new_album_submitted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviewThumb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('thumbs_up', models.BooleanField(default=False)),
                ('thumbs_down', models.BooleanField(default=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.albumreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('thumbs_up', False), ('thumbs_down', False), _connector='OR'), name='thumbs_cannot_both_be_true')],
            },
        ),
    ]
