# Generated by Django 5.2.8 on 2026-04-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_userreviewthumb'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='albumreview',
            constraint=models.UniqueConstraint(fields=('user', 'album'), name='unique_review'),
        ),
    ]
